# Generated by Django 5.2 on 2025-04-11 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cinema", "0002_seat_room"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="duration",
            field=models.DurationField(),
        ),
    ]
