# Generated by Django 5.2 on 2025-04-11 18:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cinema", "0003_alter_movie_duration"),
    ]

    operations = [
        migrations.AlterField(
            model_name="seat",
            name="screening",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="seats",
                to="cinema.screening",
            ),
        ),
    ]
